//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2007 - Infos @ http://www.17buddies.net //
//          More than 15000 maps to download!           //
//                                                      //
//      Can you play all of our maps ?? Sure not!!      //
//////////////////////////////////////////////////////////
//
// Res file generated by mikado for 17Buddies.
//
// Map Name  : de_survivor_cz
//
// Download @: http://dwl.17buddies.net/link/map/11336/de_survivor_cz.html
//
//////////////////////////////////////////////////////////
maps\de_survivor_cz_detail.txt

gfx/env/snowlake_up.tga
gfx/env/snowlake_dn.tga
gfx/env/snowlake_lf.tga
gfx/env/snowlake_rt.tga
gfx/env/snowlake_ft.tga
gfx/env/snowlake_bk.tga
 
sound/weapons/357_cock1.wav
sound/ambience/3dmthrill.wav
sound/ambience/3dmbridge.wav
sound/ambience/3dmeagle.wav
sound/ambience/wolfhowl01.wav
sound/ambience/wind1.wav
sound/ambience/wolfhowl02.wav
sound/ambience/3dmstart.wav
sound/plats/vehicle4.wav

sprites/snow.spr
sprites/flare1.spr
sprites/3dmflared.spr
sprites/3dmflaora.spr